import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import Providers from "@/components/Providers";
// aos css
import "aos/dist/aos.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "GameHub - Buy & Sale Games",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="flex flex-col items-center max-w-[1480px] mx-auto h-screen w-full">
            <Navbar></Navbar>
            <div className="w-full py-10"></div>
            <div className="flex-1 w-full">{children}</div>
            <Footer></Footer>
          </div>
        </Providers>
        <ToastContainer></ToastContainer>
      </body>
    </html>
  );
}
