import AddGamePage from "./AddGamePage";

export const metadata = {
  title: "Add Game || GameHub",
  description: "Generated by create next app",
};

const AddGame = () => {
  return <AddGamePage></AddGamePage>;
};

export default AddGame;
