export const metadata = {
  title: "Manage Your Games || GameHub",
  description: "Generated by create next app",
};

const ManageGames = () => {
  return <div>ManageGames</div>;
};

export default ManageGames;
