import ManageGamesPage from "./ManageGamesPage";

export const metadata = {
  title: "Manage Your Games || GameHub",
  description: "Generated by create next app",
};

const ManageGames = () => {
  return <ManageGamesPage></ManageGamesPage>;
};

export default ManageGames;
