import GamesPage from "./GamesPage";

export const metadata = {
  title: "All Games || GameHub",
  description: "Generated by create next app",
};
const Games = () => {
  return <GamesPage></GamesPage>;
};

export default Games;
